[character]
symbol = "ვ"

[git_status]
ahead = "@"
behind = "v"
deleted = "x"
diverged = "*"
renamed = ">"

[git_branch]
symbol = "/"

[elixir]
symbol = "Elixir "

[golang]
symbol = "Go "

[rust]
symbol = "Rust "

[package]
symbol = "Cargo "

[java]
symbol = "Java "

[python]
symbol = "Python "

[nix_shell]
symbol = "NIX "
